#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
    apt install $OTHER_INSTALLS -y
   fi
   }
_externals () {
   if [[ $OTHER_CMD != "None" ]]
   then
      $OTHER_CMD
   fi
   }
    
apt update && apt upgrade -y
apt install git -y
_other_installs
pip3 install -U pip
git clone $REPO_URL Github_Repo
cd Github_Repo
pip3 install -U -r requirements.txt
_externals
cd tobrot
curl 'https://gist.github.com/prxpostern/394cd09ab9826f47de5e6ef41854e84f/raw/config.py' -o config.py
curl 'https://gist.github.com/prxpostern/394cd09ab9826f47de5e6ef41854e84f/raw/config.py' -o sample_config.py
cd ..
python3 $PYTHON_FILE
